contact_links:
  - name: Raise Support
    url: https://pixinvent.ticksy.com/
    about: GitHub issues are for our internal purpose only. Please raise support ticket on our support portal for any kind of query.
